Name:           ros-kinetic-pyros-test
Version:        0.0.5
Release:        0%{?dist}
Summary:        ROS pyros_test package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-message-runtime >= 0.4.12
Requires:       ros-kinetic-rospy >= 1.11.19
Requires:       ros-kinetic-std-msgs >= 0.5.9
BuildRequires:  ros-kinetic-catkin >= 0.6.18
BuildRequires:  ros-kinetic-message-generation >= 0.2.10
BuildRequires:  ros-kinetic-roslint >= 0.10.0
BuildRequires:  ros-kinetic-rospy >= 1.11.19
BuildRequires:  ros-kinetic-rostest >= 1.11.19
BuildRequires:  ros-kinetic-rostopic >= 1.11.19
BuildRequires:  ros-kinetic-rosunit >= 1.11.12
BuildRequires:  ros-kinetic-std-msgs >= 0.5.9

%description
Basic test nodes for Pyros dynamic ROS interface

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Tue Oct 25 2016 AlexV <asmodehn@gmail.com> - 0.0.5-0
- Autogenerated by Bloom

* Fri Sep 02 2016 AlexV <asmodehn@gmail.com> - 0.0.4-0
- Autogenerated by Bloom

